import { Inter } from 'next/font/google';
import './globals.css';
import Provider from './redux/provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <link
          rel='icon'
          href='https://assets.nflxext.com/ffe/siteui/common/icons/nficon2016.ico'
          sizes='any'
        ></link>
      </head>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
